arch:
  - amd64
  - ppc64le
sudo: true
language: haskell

git:
  depth: 5

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

  - |
    curl -sSL https://get.haskellstack.org/ | sh
    stack --version
    stack build \
          --test \
          --no-run-tests \
          --ghc-options=-Werror

script:
  - stack test
